export const companyIcons: Record<string, string> = {
  "Amazon": "/icons/amazon.png",
  "Microsoft": "/icons/microsoft.png",
  "Google": "/icons/google.png",
  "Meta": "/icons/facebook.png",
  "Goldman Sachs": "/icons/goldman-sachs.png",
  "Bloomberg": "/icons/bloomberg.png",
  "Arista Networks": "/icons/arista-networks.png",
  "IBM": "/icons/ibm.png",
  "TCS": "/icons/tcs.png",
  "Apple": "/icons/apple.png",
  "PayPal": "/icons/paypal.png",
  "Yandex": "/icons/yandex.png",
  "Asana": "/icons/asana.png",
  "Nvidia": "/icons/nvidia.png",
  "Zoho": "/icons/zoho.png",
  "ThousandEyes": "/icons/thousandeyes.png",
  "Uber": "/icons/uber.png",
  "Adobe": "/icons/adobe.png",
  "Citadel": "/icons/citadel.png",
  "Walmart Labs": "/icons/walmart-labs.png",
  "Nutanix": "/icons/nutanix.png",
  "Oracle": "/icons/oracle.png",
  "Cisco": "/icons/cisco.png",
  "Spotify": "/icons/spotify.png",
  "Disney": "/icons/disney.jpeg",
  "Twilio": "/icons/twilio.png",
  "Capital One": "/icons/capital-one.png",
  "Docusign": "/icons/docusign.png",
  "TikTok": "/icons/tiktok.png",
  "Rippling": "/icons/rippling.jpeg",
  "Databricks": "/icons/databricks.png",
  "Robinhood": "/icons/robinhood.png",
  "Josh Technology": "/icons/josh-technology.png",
  "Epic Systems": "/icons/epic-systems.png",
  "Yahoo": "/icons/yahoo.png",
  "Roblox": "/icons/roblox.png",
  "Flipkart": "/icons/flipkart.png",
  "Snowflake": "/icons/snowflake.png",
  "Mastercard": "/icons/mastercard.svg",
  "Squarespace": "/icons/squarespace.png",
  "Intuit": "/icons/intuit.png",
  "LinkedIn": "/icons/linkedin.png",
  "Bank of America": "/icons/bank-of-america.svg",
  "Intel": "/icons/intel.png",
  "Netflix": "/icons/netflix.png",
  "Karat": "/icons/karat.png",
  "Salesforce": "/icons/salesforce.png",
  "ServiceNow": "/icons/servicenow.png",
  "MakeMyTrip": "/icons/makemytrip.png",
  "Infosys": "/icons/infosys.png",
  "Snap": "/icons/snap.jpeg",
  "tcs": "/icons/tcs.jpeg",
  "Anduril": "/icons/anduril.svg",
  "Wix": "/icons/wix.jpeg",
  "Pinterest": "/icons/pinterest.png",
  "J.P. Morgan": "/icons/jp.png",
  "Deloitte": "/icons/deloitte.jpeg",
  "Myntra": "/icons/myntra.png",
  "Atlassian": "/icons/atlassian.png",
  "Grammarly": "/icons/grammarly.png",
  "Accenture": "/icons/accenture.png",
  "Booking.com": "/icons/booking.jpeg",
  "Akamai": "/icons/akamai.png",
  "Toast": "/icons/toast.png",
  "Sigmoid": "/icons/sigmoid.png",
  "Expedia": "/icons/expedia.jpeg",
  "AT&T": "/icons/att.png",
  "Qualcomm": "/icons/qualcomm.png",
  "American Express": "/icons/american-express.png",
  "Agoda": "/icons/agoda.png",
  "Visa": "/icons/visa.png",
  "Pure Storage": "/icons/pure-storage.png",
  "Urban Company": "/icons/urban-company.png",
  "Zomato": "/icons/zomato.png",
  "Tesla": "/icons/tesla.png",
  "Hubspot": "/icons/hubspot.png",
  "BitGo": "/icons/bitgo.jpeg",
  "DoorDash": "/icons/doordash.png",
  "Swiggy": "/icons/swiggy.png",
  "IXL": "/icons/ixl.png",
  "ByteDance": "/icons/bytedance.png",
  "Cognizant": "/icons/cognizant.png",
  "MongoDB": "/icons/mongodb.png",
  "Lyft": "/icons/lyft.png",
  "Oscar Health": "/icons/oscar.png",
  "Splunk": "/icons/splunk.jpeg",
  "RBC": "/icons/rbc.svg",
  "Coupang": "/icons/coupang.png",
  "Quora": "/icons/quora.png",
  "Airbnb": "/icons/airbnb.png",
  "Samsung": "/icons/samsung.png",
  "Palo Alto Networks": "/icons/palo.png",
  "Okta": "/icons/okta.jpeg",
  "Morgan Stanley": "/icons/morgan-stanley.png",
  "eBay": "/icons/ebay.jpeg",
  "Autodesk": "/icons/autodesk.png",
};
